config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'products#index'

  resources :products, only: [:index, :new, :create, :show, :destroy]
  resources :users
  resource :cart, only: [:show, :destroy] do
    get :add, on: :member
    post :order, on: :member

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :account, optional: true
  has_and_belongs_to_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  attr_accessor :user_mail, :comment

  def show
    @cart = Cart.find(session[:cart_id])
    @products = @cart.products
  end

  def add
    @cart = Cart.find(session[:cart_id])
    @product = Product.find(params[:product_id])
    @cart.products << @product
  end

  def destroy
    @cart = Cart.find(session[:cart_id])
    @product = Product.find(params[:product_id])
    @cart.products.destroy(@product)
    flash[:warning] = t(:Removed_from_cart_successfully)
    redirect_to cart_path
  end

  def order
    @user_mail = current_user.email
    CartMailer.product_ordered(@user_mail).deliver_now
    flash[:success] = t('.product_ordered_successfully_wait_for_delievery')
    redirect_to cart_path
  end

end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_partial
    @products.empty? ? 'empty' : 'list'
  end
end

app/views/carts/_empty.html.haml
%p= 'No products in your cart!'
%p= image_tag 'empty.png'

app/views/carts/_list.html.haml
%p{id:"notice"}= notice

.container
  .panel.panel-default
    .panel-heading
      %h3= t('.cart')
    %table.table
      %thead
        %tr
          %th= t('.name')
          %th= t('.price')
          %th= t('.description')

      %tbody
        - @products.each do |product|
          %tr
            %td= product.name
            %td= product.price
            %td= product.description
            %td= link_to t('.destroy'), cart_path(cart_id: @cart.id, product_id: product.id), method: :delete, class: 'btn btn-danger'


  %br
    %td= link_to t('.back'), products_path, class: 'btn btn-default'

    %button.btn.btn-primary{"data-target" => "#exampleModal", "data-toggle" => "modal", "data-whatever" => "@mdo", :type => "button"}= t('.order')
    =render 'modal'

    %th= 'Total price:'
    =@products.sum(:price)

app/views/carts/_modal.html.haml
#exampleModal.modal.fade{"aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header

        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title= t('.order_form')

      .modal-body

        = form_tag order_cart_path do

          .form-group
            = label_tag= t('.email')
            = current_user.email

          .form-group
            = label_tag = t('.comment')
            = text_field 'comment', nil, class: 'form-control', placeholder: t('.comment'), type: 'text'

          = submit_tag t('.order'), class: 'btn btn-primary'

app/views/carts/add.js.erb
var message = '<%= t('carts.add')%>'
alert(message);

app/views/carts/show.html.haml
= render 'list'