config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'products#index'

  resources :products, only: [:index, :new, :create, :show, :destroy]
  resources :users
  resource :cart, only: [:show, :destroy] do
    get :add, on: :member
    post :order, on: :member

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :carts
  has_many :product_assets
  attr_ :asset_attributes, :product_asset_attributes

  accepts_nested_attributes_for :product_assets

  has_one :address, as: :addressable

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @products = Product.order(params[:sort])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    raise Exception.new
    @product = Product.new
  end

  def create
    Product.create!(product_params)
    redirect_to products_path
    flash[:success] = t(:Created_successfully)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:warning] = t(:Deleted_successfully)
    redirect_to products_path
  end

  private

  def product_params
    # params.require('product').permit(:name, :price, :description).permit(:product_asset_attributes)
    # params.permit_all_parameters = true
    params.permit(:product, :product_asset_attributes)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.container-fluid
  .row
    .col-md-4
      = form_for @product do |product_form|

        %h3= t('.new_product')

        -#= label_tag t('.name')
        -#%input.form-control{:placeholder => t('.name'), :type => 'text', :name => 'name'}
        = product_form.label :name
        = product_form.text_field :name, class: 'form-control'

        %br
        = label_tag t('.price')
        %input.form-control{placeholder: t('.price'), type: 'integer', name: 'price'}

        %br
        -#= label_tag t('.description')
        -#%input.form-control{:placeholder => t('.description'), :type => 'text', :name => 'description'}
        = product_form.label :description
        = product_form.text_field :description, class: 'form-control'
        %br
        = product_form.fields_for :product_asset_attributes, @product.product_assets.new do |asset_form|
          = asset_form.label :desc
          = asset_form.text_field :desc, class: 'form-control'

        %p= submit_tag t('.save'), class: 'btn btn-success'

        %p= link_to t('.back'), products_path, class: 'btn btn-default'

app/views/products/edit.html.haml
%h1 Editing Product

= render 'form', product: @product

= link_to 'Show', @product
= link_to 'Back', products_path

app/views/products/index.html.haml
%p{id:"notice"}= notice

.container
    .panel.panel-default
        .panel-heading
            %h3= t('.products')
        %table.table
            %thead
                %tr
                    %th= link_to t('.name'), :sort => 'name'
                    %th= link_to t('.price'), :sort => 'price'
                    %th= t('.description')

            %tbody
            - @products.each do |product|
                %tr
                    %td= product.name
                    %td= product.price
                    %td= product.description
                    %td= link_to t('.show'), product, class: 'btn btn-info'
                    %td= link_to t('.buy'), add_cart_path(product_id: product.id), remote: true, class: 'btn btn-success'
                    %td= link_to t('.destroy'), product, method: :delete, class: 'btn btn-danger', data: { confirm: t('.confirm_message') }

    %br
    %td= link_to t('.new_product'), new_product_path, class: 'btn btn-default'

app/views/products/new.html.haml
%p{id:"notice"}= notice

= render 'form', product: @product

app/views/products/show.html.haml
%p{id:"notice"}= notice

.container
  .panel.panel-default
    .panel-heading
      %h3= t('.product_description')
    %table.table
      %thead
        %tr
          %th= t('.name')
          %th= t('.price')
          %th= t('.description')

      %tbody
        %tr
          %td= @product.name
          %td= @product.price
          %td= @product.description
          %td= link_to t('.destroy'), @product, method: :delete, class: 'btn btn-danger'

  %td= link_to t('.back'), products_path, class: 'btn btn-default'