config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'products#index'

  resources :products, only: [:index, :new, :create, :show, :destroy]
  resources :users
  resource :cart, only: [:show, :destroy] do
    get :add, on: :member
    post :order, on: :member

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_count.html.haml
%span.badge=  "#{Cart.find(session[:cart_id]).products.count}"

app/views/layouts/_flash.html.haml
- if flash[:success]
  .alert.alert-success{:role => 'alert'}
    = flash[:success]

- if flash[:warning]
  .alert.alert-danger{:role => 'alert'}
    = flash[:warning]

app/views/layouts/_lang.html.haml
.dropup
  %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    Language
    %span.caret
  %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
    %li
      = link_to image_tag('uk.png', size: '20x20') + 'En', locale: :en
    %li
      = link_to image_tag('ua.png', size: '20x20') + 'UA', locale: :ua
    %li
      = link_to image_tag('pl.png', size: '20x20') + 'PL', locale: :pl

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title Ishop
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .header
      .row
        %div.col-md-1.text-center= link_to image_tag('ishop.png'), products_path
        %div.col-md-1.text-center= link_to image_tag('products_2.png'), products_path
        %div.col-md-1.text-center= link_to image_tag('users-3.png'), users_path
        %div.col-md-2.pull-right.text-right
          = link_to image_tag('cart_2.png'), cart_path
          =render 'layouts/count'


    = render 'layouts/flash'

    = yield

    .footer
      .row
        %div.col-md-2
          = render 'layouts/lang'